name: Build, Test and Deploy
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
